//! Emit `data_uses.rs` catalog source.

use std::fs;
use std::path::Path;

use crate::{ConnectionHopKind, DataUseScanError, OpKind, ScanHit, TargetKind};

/// Write the include file that defines `data_use_catalog()`.
pub fn write_snapshot(out_dir: &Path, hits: &[ScanHit]) -> Result<(), DataUseScanError> {
    fs::create_dir_all(out_dir).map_err(|e| DataUseScanError::Io {
        path: out_dir.to_path_buf(),
        message: e.to_string(),
    })?;
    let dest = out_dir.join("data_uses.rs");
    let body = render_snapshot(hits);
    fs::write(&dest, body).map_err(|e| DataUseScanError::Io {
        path: dest,
        message: e.to_string(),
    })?;
    Ok(())
}

pub(crate) fn render_snapshot(hits: &[ScanHit]) -> String {
    let mut code = String::new();
    code.push_str("// @generated by uf-valence-data-use-scan — do not edit\n\n");
    code.push_str("/// Every declared data use in this deployment, collected at build time.\n");
    code.push_str("///\n");
    code.push_str("/// Install the result once at boot with `DataUseCatalog::install`.\n");
    code.push_str("#[must_use]\n");
    code.push_str("pub fn data_use_catalog() -> ::valence::data_use::DataUseCatalog {\n");
    code.push_str("    #[allow(unused_imports)]\n");
    code.push_str("    use ::valence::data_use::{ConnectionHop, ConnectionHopKind, DataOp, DataUse, DataUseCatalog, DataUseTarget};\n");
    code.push_str("    DataUseCatalog::from_entries(vec![\n");
    for hit in hits {
        code.push_str("        DataUse {\n");
        code.push_str(&format!(
            "            purpose: String::from({}),\n",
            escape_str_lit(&hit.purpose)
        ));
        code.push_str(&format!(
            "            file: String::from({}),\n",
            escape_str_lit(&hit.file)
        ));
        code.push_str(&format!("            line: {},\n", hit.line));
        code.push_str(&format!(
            "            crate_name: String::from({}),\n",
            escape_str_lit(&hit.crate_name)
        ));
        code.push_str(&format!(
            "            repository: String::from({}),\n",
            escape_str_lit(&hit.repository)
        ));
        code.push_str(&format!(
            "            target: {},\n",
            render_target(&hit.target)
        ));
        code.push_str(&format!("            op: {},\n", render_op(hit.op)));
        code.push_str(&format!(
            "            method: String::from({}),\n",
            escape_str_lit(&hit.method)
        ));
        code.push_str(&format!(
            "            connection: {},\n",
            render_connection(hit.connection_field.as_deref(), hit.connection_kind)
        ));
        code.push_str(&format!(
            "            referenced_schema: {},\n",
            render_opt_string(hit.referenced_schema.as_deref())
        ));
        code.push_str("            via_trait: None,\n");
        code.push_str("        },\n");
    }
    code.push_str("    ])\n");
    code.push_str("}\n");
    code
}

fn render_target(target: &TargetKind) -> String {
    match target {
        TargetKind::Schema(name) => format!(
            "DataUseTarget::Schema(String::from({}))",
            escape_str_lit(name)
        ),
        TargetKind::Trait(name) => format!(
            "DataUseTarget::Trait(String::from({}))",
            escape_str_lit(name)
        ),
        TargetKind::Unscoped => "DataUseTarget::Unscoped".to_string(),
    }
}

fn render_op(op: OpKind) -> String {
    match op {
        OpKind::Read => "DataOp::Read".into(),
        OpKind::Create => "DataOp::Create".into(),
        OpKind::Update => "DataOp::Update".into(),
        OpKind::Delete => "DataOp::Delete".into(),
    }
}

fn render_opt_string(value: Option<&str>) -> String {
    match value {
        Some(s) => format!("Some(String::from({}))", escape_str_lit(s)),
        None => "None".into(),
    }
}

fn render_connection(field: Option<&str>, kind: Option<ConnectionHopKind>) -> String {
    let (Some(field), Some(kind)) = (field, kind) else {
        return "None".into();
    };
    let kind = match kind {
        ConnectionHopKind::ForwardGet => "ConnectionHopKind::ForwardGet",
        ConnectionHopKind::Relate => "ConnectionHopKind::Relate",
    };
    format!(
        "Some(ConnectionHop {{ field: String::from({}), kind: {kind} }})",
        escape_str_lit(field)
    )
}

fn escape_str_lit(s: &str) -> String {
    // Prefer raw strings when the purpose contains quotes or backslashes.
    if s.contains('\\') || s.contains('"') || s.contains('\n') {
        // Find a `#` count that does not appear in the payload terminator.
        let mut hashes = 1;
        loop {
            let delim = format!("{}\"", "#".repeat(hashes));
            if !s.contains(&delim) {
                break;
            }
            hashes += 1;
        }
        let pounds = "#".repeat(hashes);
        format!("r{pounds}\"{s}\"{pounds}")
    } else {
        format!("\"{s}\"")
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn hit(purpose: &str) -> ScanHit {
        ScanHit {
            purpose: purpose.into(),
            file: "product/src/lib.rs".into(),
            line: 9,
            crate_name: "product".into(),
            repository: "https://github.com/acme/product".into(),
            target: TargetKind::Schema("todo".into()),
            op: OpKind::Read,
            method: "get_owner".into(),
            connection_field: Some("owner".into()),
            connection_kind: Some(ConnectionHopKind::ForwardGet),
            referenced_schema: Some("user".into()),
        }
    }

    #[test]
    fn emit_compiles_shape() {
        let code = render_snapshot(&[hit(r#"We load "your" account \ safely."#), hit("plain")]);
        let file = syn::parse_file(&code).expect("generated catalog parses as Rust");
        let fns: Vec<String> = file
            .items
            .iter()
            .filter_map(|item| match item {
                syn::Item::Fn(f) => Some(f.sig.ident.to_string()),
                _ => None,
            })
            .collect();
        assert_eq!(fns, vec!["data_use_catalog".to_string()]);
        assert!(code.contains("::valence::data_use::DataUseCatalog"));
        assert!(code.contains(
            "connection: Some(ConnectionHop { field: String::from(\"owner\"), kind: ConnectionHopKind::ForwardGet })"
        ));
        assert!(code.contains("referenced_schema: Some(String::from(\"user\"))"));
        assert!(code.contains(r##"String::from(r#"We load "your" account \ safely."#)"##));
        assert!(!code.contains("DATA_USES"));
    }

    #[test]
    fn empty_catalog_still_defines_function() {
        let code = render_snapshot(&[]);
        assert!(syn::parse_file(&code).is_ok());
        assert!(code.contains("DataUseCatalog::from_entries(vec![\n    ])"));
    }
}
