#!/usr/bin/env bash
# Launch two campaign EC2 hosts: e2e + bench (parallel).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${ROOT}/instances.env"

AWS_REGION="${AWS_REGION:-us-west-2}"
KEY_NAME="${AWS_KEY_NAME:-valence-campaign}"
SSH_USER="${SSH_USER:-ubuntu}"
INSTANCE_TYPE="${VALENCE_CAMPAIGN_INSTANCE_TYPE:-c6i.xlarge}"
VOLUME_GIB="${VALENCE_CAMPAIGN_VOLUME_GIB:-80}"

AMI_ID="${AWS_AMI_ID:-$(aws ec2 describe-images --region "$AWS_REGION" \
  --owners 099720109477 \
  --filters "Name=name,Values=ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-*" \
            "Name=state,Values=available" \
  --query 'sort_by(Images,&CreationDate)[-1].ImageId' --output text)}"

MY_IP="$(curl -sf https://checkip.amazonaws.com || echo "0.0.0.0")"
VPC_ID="$(aws ec2 describe-vpcs --region "$AWS_REGION" \
  --filters Name=isDefault,Values=true \
  --query 'Vpcs[0].VpcId' --output text)"
SUBNET_ID="$(aws ec2 describe-subnets --region "$AWS_REGION" \
  --filters "Name=vpc-id,Values=${VPC_ID}" "Name=default-for-az,Values=true" \
  --query 'Subnets[0].SubnetId' --output text)"

SG_NAME="valence-campaign-$(date +%Y%m%d-%H%M%S)"
SG_ID="$(aws ec2 create-security-group --region "$AWS_REGION" \
  --group-name "$SG_NAME" --description "Valence E2E/bench campaign" \
  --vpc-id "$VPC_ID" --query GroupId --output text)"

aws ec2 authorize-security-group-ingress --region "$AWS_REGION" --group-id "$SG_ID" \
  --ip-permissions \
  "IpProtocol=tcp,FromPort=22,ToPort=22,IpRanges=[{CidrIp=${MY_IP}/32,Description=ssh-operator}]" \
  >/dev/null

# Intra-SG for wire services if we later split data/runner.
aws ec2 authorize-security-group-ingress --region "$AWS_REGION" --group-id "$SG_ID" \
  --ip-permissions \
  "IpProtocol=tcp,FromPort=5432,ToPort=5432,UserIdGroupPairs=[{GroupId=${SG_ID},Description=postgres}]" \
  "IpProtocol=tcp,FromPort=27017,ToPort=27017,UserIdGroupPairs=[{GroupId=${SG_ID},Description=mongodb}]" \
  "IpProtocol=tcp,FromPort=6379,ToPort=6379,UserIdGroupPairs=[{GroupId=${SG_ID},Description=redis}]" \
  >/dev/null

launch_one() {
  local role="$1"
  local name="valence-campaign-${role}"
  aws ec2 run-instances --region "$AWS_REGION" \
    --image-id "$AMI_ID" \
    --instance-type "$INSTANCE_TYPE" \
    --key-name "$KEY_NAME" \
    --subnet-id "$SUBNET_ID" \
    --security-group-ids "$SG_ID" \
    --block-device-mappings "[{\"DeviceName\":\"/dev/sda1\",\"Ebs\":{\"VolumeSize\":${VOLUME_GIB},\"VolumeType\":\"gp3\",\"DeleteOnTermination\":true}}]" \
    --tag-specifications "ResourceType=instance,Tags=[{Key=Name,Value=${name}},{Key=Project,Value=valence-campaign},{Key=Role,Value=${role}}]" \
    --query 'Instances[0].InstanceId' --output text
}

E2E_IID="$(launch_one e2e)"
BENCH_IID="$(launch_one bench)"

echo "Waiting for ${E2E_IID} ${BENCH_IID}..."
aws ec2 wait instance-running --region "$AWS_REGION" --instance-ids "$E2E_IID" "$BENCH_IID"

# Public IPs can lag briefly after running.
sleep 5
describe_ip() {
  local iid="$1"
  aws ec2 describe-instances --region "$AWS_REGION" --instance-ids "$iid" \
    --query 'Reservations[0].Instances[0].[PrivateIpAddress,PublicIpAddress,InstanceType]' --output text
}

read -r E2E_PRIVATE E2E_PUBLIC E2E_TYPE <<<"$(describe_ip "$E2E_IID")"
read -r BENCH_PRIVATE BENCH_PUBLIC BENCH_TYPE <<<"$(describe_ip "$BENCH_IID")"

cat >"$ENV_FILE" <<EOF
# Generated by provision.sh — do not commit secrets
AWS_REGION=${AWS_REGION}
AWS_KEY_NAME=${KEY_NAME}
SSH_USER=${SSH_USER}
SSH_KEY_PATH=\${SSH_KEY_PATH:-\$HOME/.ssh/id_ed25519}
SECURITY_GROUP_ID=${SG_ID}
INSTANCE_E2E=${E2E_IID}
E2E_PRIVATE_IP=${E2E_PRIVATE}
E2E_PUBLIC_IP=${E2E_PUBLIC}
E2E_INSTANCE_TYPE=${E2E_TYPE}
INSTANCE_BENCH=${BENCH_IID}
BENCH_PRIVATE_IP=${BENCH_PRIVATE}
BENCH_PUBLIC_IP=${BENCH_PUBLIC}
BENCH_INSTANCE_TYPE=${BENCH_TYPE}
VALENCE_BENCH_HARDWARE=${INSTANCE_TYPE}
EOF

echo "Wrote ${ENV_FILE}"
cat "$ENV_FILE"
